[package]
name = "vector-bench"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bencher.workspace = true
vector = { path = "..", package = "opendata-vector" }
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
